development:
  environment: "sandbox"
  username: "artsoftPm_api1.business.com"
  password: "8KSTGGPBPL4WLFXH"
  signature: "AFcWxV21C7fd0v3bYYYRCpSSRl31AmA8V.iyHwboZRLjPVUWiUl0wLfw"
  application_id: "APP-80W284485P519543T"
  api_cert_file:

test:
  environment: "sandbox"
  username: "artsoftPm_api1.business.com"
  password: "8KSTGGPBPL4WLFXH"
  signature: "AFcWxV21C7fd0v3bYYYRCpSSRl31AmA8V.iyHwboZRLjPVUWiUl0wLfw"
  application_id: "APP-80W284485P519543T"
  api_cert_file: "/path/to_cert"

production:
  environment: "production"
  username: "artsoftPm_api1.business.com"
  password: "8KSTGGPBPL4WLFXH"
  signature: "AFcWxV21C7fd0v3bYYYRCpSSRl31AmA8V.iyHwboZRLjPVUWiUl0wLfw"
  application_id: "APP-80W284485P519543T"
  api_cert_file: "/path/to_cert"