# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fa0fa89f1e38ae06650358e95b36a1ca0d8aa7871fd3fe54f011a3e6f88f98d184e93aaa50903c2da558d6fa49fa457bc4c958936a5a63977f2a8d3f3db189fe

test:
  secret_key_base: bcf0e7f3933cd829e72252d2b2bf30bd3d06f16143ea071a412d358901a7c0e356cfabb00ba4a579ef77908fde8d57d413125dc9387441338097aa9c5c0b1296

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
