# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3a49e1d477a02cc8b6c55b5e887cb043b49b0837fda8ac96e856d3281b3eaecd76ebc88697cd9da1e6f40649c80b39d5cc29aaa3a6d66d67ca3c5e2c078835de

test:
  secret_key_base: dc121434df7b484a6178c385a319c7a97059bf56b256f8828968b10df5bb646a001b80a5df4d20b9c96fb5993ee1df2b9c52f273951841749a0902b770903c6e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
